### ISSUE TITLE
wireframe for "Create an eMQTT dashboard to fit MQT analytics data structure"

### ISSUE THREAD

**Issue by bajiat** [apinf/emq-analytics-dashboard#5]
_From @Nazarah on November 4, 2016 13:44_

#1881

_Copied from original issue: apinf/platform#1888_

**Comment by bajiat** [comment]
_From @Nazarah on November 17, 2016 14:50_

Keeping it into Blocked as the main task would start once the dashboard is ready to be placed in APINF.
I can suggest GUI changes or additions that time.

**Comment by bajiat** [comment]
@Nazarah Do you still want to keep this issue or should we close it?

**Comment by Nazarah** [comment]
#3 is related there

**Comment by Nazarah** [comment]
@55 and I are working on redesigning the dashboard. So this can be closed.
