### ISSUE TITLE
Generate sample analytics data & measure request/response timings for larger time range

### ISSUE THREAD

**Issue by frenchbread** [apinf/emq-analytics-dashboard#8]
### Def. of done

- [ ] Generate sample analytics data (that much, so it's enough for metrics collection)
- [ ] Collect metrics for following date-ranges:
    - [ ] 6 months
    - [ ] 12 months
    - [ ] 1.5 year
    - [ ] 2 years

**Comment by bajiat** [comment]
Done. Closing the issue.
