### ISSUE TITLE
Add multiselect support to bootstrap-select picker

### ISSUE THREAD

**Issue by frenchbread** [apinf/emq-analytics-dashboard#9]
Related PR: https://github.com/apinf/emq-analytics-dashboard/pull/7

**Comment by bajiat** [comment]
@frenchbread Should this issue be closed? As far as I can see, the related PR was merged.  Please close, if it should be closed.

**Comment by frenchbread** [comment]
@bajiat multiselect feature was not implemented yet. But it might not have critical need since it is more like an enhancement and can be implemented after integration with apinf.

**Comment by marla-singer** [comment]
Closed it as outdated
